### ISSUE TITLE
TODO before submitting to conference

### ISSUE THREAD

**Issue by AndreasMadsen** [AndreasMadsen/nlp-roar-interpretability#34]
**must do**

- [ ] Remove reference to compute canada. i.e. delete `batch_jobs`, `*_job.sh`, and `Makefile` from zip.
- [x] Rename `comp550` to `nlproar` or something similar.
- [ ] Anonymize `setup.py` in zip.

**should do**

- [x] update doc-strings
